### PR TITLE
fix: ci failing with find command

### PR DESCRIPTION
**Pull request by felipecrs**
- As suggested by @carlocorradini at https://github.com/vscode-shellcheck/shellcheck-binaries/pull/1#issuecomment-1414769448

### CODE REVIEW

**Comment by felipecrs** [comment]
@carlocorradini I also noticed that the Windows binary is generated as if it was a x84_64 one, but I think it's actually 32bits. Isn't it?

**Comment by carlocorradini** [comment]
@felipecrs Close this I will push a new PR with some fixes :)

**Comment by carlocorradini** [comment]
> @carlocorradini I also noticed that the Windows binary is generated as if it was a x84_64 one, but I think it's actually 32bits. Isn't it?

I'mm modify to `x86` only. It is good for you?

**Comment by felipecrs** [comment]
> I'mm modify to x86 only. It is good for you?

I'm not sure if x86 would be the correct term for Windows 32 bits... On Node it appears to be ia32, some other places it's i386, i486, i686.

But yes, x86 should be good.

**Comment by carlocorradini** [comment]
It is to stay compliant with ShellCheck :/

**Comment by carlocorradini** [comment]
@felipecrs See PR #3

**Pull request closed without merging**
